forge "http://forge.puppetlabs.com"

#dhutty doesn't seem to be releasing to the forge with any frenquency
mod 'dhutty/nginx', git: 'https://github.com/dhutty/puppet-nginx.git'

mod 'puppetlabs/postgresql'
mod 'maestrodev/rvm'
